export default {
    data: [{
        "image": "training/1.png",
        "isSquare": true
    }, {
        "image": "training/2.png",
        "isSquare": false
    }, {
        "image": "training/3.png",
        "isSquare": false
    }, {
        "image": "training/4.png",
        "isSquare": false
    }, {
        "image": "training/5.png",
        "isSquare": true
    }, {
        "image": "training/6.png",
        "isSquare": false
    }, {
        "image": "training/7.png",
        "isSquare": false
    }, {
        "image": "training/8.png",
        "isSquare": true
    }, {
        "image": "training/9.png",
        "isSquare": false
    }, {
        "image": "training/10.png",
        "isSquare": false
    }, {
        "image": "training/11.png",
        "isSquare": true
    }, {
        "image": "training/12.png",
        "isSquare": false
    }, {
        "image": "training/13.png",
        "isSquare": true
    }, {
        "image": "training/14.png",
        "isSquare": false
    }, {
        "image": "training/15.png",
        "isSquare": false
    }, {
        "image": "training/16.png",
        "isSquare": true
    }, {
        "image": "training/17.png",
        "isSquare": false
    }, {
        "image": "training/18.png",
        "isSquare": false
    }, {
        "image": "training/19.png",
        "isSquare": false
    }, {
        "image": "training/20.png",
        "isSquare": false
    }, {
        "image": "training/21.png",
        "isSquare": false
    }, {
        "image": "training/22.png",
        "isSquare": false
    }, {
        "image": "training/23.png",
        "isSquare": false
    }, {
        "image": "training/24.png",
        "isSquare": true
    }, {
        "image": "training/25.png",
        "isSquare": false
    }, {
        "image": "training/26.png",
        "isSquare": false
    }, {
        "image": "training/27.png",
        "isSquare": true
    }, {
        "image": "training/28.png",
        "isSquare": false
    }, {
        "image": "training/29.png",
        "isSquare": false
    }, {
        "image": "training/30.png",
        "isSquare": false
    }, {
        "image": "training/31.png",
        "isSquare": false
    }, {
        "image": "training/32.png",
        "isSquare": false
    }, {
        "image": "training/33.png",
        "isSquare": false
    }, {
        "image": "training/34.png",
        "isSquare": false
    }, {
        "image": "training/35.png",
        "isSquare": false
    }, {
        "image": "training/36.png",
        "isSquare": false
    }, {
        "image": "training/37.png",
        "isSquare": false
    }, {
        "image": "training/38.png",
        "isSquare": false
    }, {
        "image": "training/39.png",
        "isSquare": false
    }, {
        "image": "training/40.png",
        "isSquare": false
    }, {
        "image": "training/41.png",
        "isSquare": false
    }, {
        "image": "training/42.png",
        "isSquare": false
    }, {
        "image": "training/43.png",
        "isSquare": false
    }, {
        "image": "training/44.png",
        "isSquare": false
    }, {
        "image": "training/45.png",
        "isSquare": false
    }, {
        "image": "training/46.png",
        "isSquare": false
    }, {
        "image": "training/47.png",
        "isSquare": false
    }, {
        "image": "training/48.png",
        "isSquare": false
    }, {
        "image": "training/49.png",
        "isSquare": false
    }, {
        "image": "training/50.png",
        "isSquare": false
    }, {
        "image": "training/51.png",
        "isSquare": false
    }, {
        "image": "training/52.png",
        "isSquare": false
    }, {
        "image": "training/53.png",
        "isSquare": false
    }, {
        "image": "training/54.png",
        "isSquare": false
    }, {
        "image": "training/55.png",
        "isSquare": false
    }, {
        "image": "training/56.png",
        "isSquare": false
    }, {
        "image": "training/57.png",
        "isSquare": false
    }, {
        "image": "training/58.png",
        "isSquare": false
    }, {
        "image": "training/59.png",
        "isSquare": true
    }, {
        "image": "training/60.png",
        "isSquare": false
    }, {
        "image": "training/61.png",
        "isSquare": false
    }, {
        "image": "training/62.png",
        "isSquare": false
    }, {
        "image": "training/63.png",
        "isSquare": false
    }, {
        "image": "training/64.png",
        "isSquare": false
    }, {
        "image": "training/65.png",
        "isSquare": false
    }, {
        "image": "training/66.png",
        "isSquare": false
    }, {
        "image": "training/67.png",
        "isSquare": false
    }, {
        "image": "training/68.png",
        "isSquare": false
    }, {
        "image": "training/69.png",
        "isSquare": false
    }, {
        "image": "training/70.png",
        "isSquare": false
    }, {
        "image": "training/71.png",
        "isSquare": false
    }, {
        "image": "training/72.png",
        "isSquare": false
    }, {
        "image": "training/73.png",
        "isSquare": false
    }, {
        "image": "training/74.png",
        "isSquare": false
    }, {
        "image": "training/75.png",
        "isSquare": false
    }, {
        "image": "training/76.png",
        "isSquare": false
    }, {
        "image": "training/77.png",
        "isSquare": false
    }, {
        "image": "training/78.png",
        "isSquare": false
    }, {
        "image": "training/79.png",
        "isSquare": false
    }, {
        "image": "training/80.png",
        "isSquare": false
    }, {
        "image": "training/81.png",
        "isSquare": false
    }, {
        "image": "training/82.png",
        "isSquare": false
    }, {
        "image": "training/83.png",
        "isSquare": false
    }, {
        "image": "training/84.png",
        "isSquare": false
    }, {
        "image": "training/85.png",
        "isSquare": false
    }, {
        "image": "training/86.png",
        "isSquare": false
    }, {
        "image": "training/87.png",
        "isSquare": false
    }, {
        "image": "training/88.png",
        "isSquare": false
    }, {
        "image": "training/89.png",
        "isSquare": false
    }, {
        "image": "training/90.png",
        "isSquare": true
    }, {
        "image": "training/91.png",
        "isSquare": false
    }, {
        "image": "training/92.png",
        "isSquare": false
    }, {
        "image": "training/93.png",
        "isSquare": false
    }, {
        "image": "training/94.png",
        "isSquare": true
    }, {
        "image": "training/95.png",
        "isSquare": false
    }, {
        "image": "training/96.png",
        "isSquare": false
    }, {
        "image": "training/97.png",
        "isSquare": false
    }, {
        "image": "training/98.png",
        "isSquare": false
    }, {
        "image": "training/99.png",
        "isSquare": false
    }, {
        "image": "training/100.png",
        "isSquare": false
    }, {
        "image": "training/101.png",
        "isSquare": false
    }, {
        "image": "training/102.png",
        "isSquare": false
    }, {
        "image": "training/103.png",
        "isSquare": false
    }, {
        "image": "training/104.png",
        "isSquare": false
    }, {
        "image": "training/105.png",
        "isSquare": false
    }, {
        "image": "training/106.png",
        "isSquare": false
    }, {
        "image": "training/107.png",
        "isSquare": false
    }, {
        "image": "training/108.png",
        "isSquare": false
    }, {
        "image": "training/109.png",
        "isSquare": true
    }, {
        "image": "training/110.png",
        "isSquare": false
    }, {
        "image": "training/111.png",
        "isSquare": false
    }, {
        "image": "training/112.png",
        "isSquare": false
    }, {
        "image": "training/113.png",
        "isSquare": false
    }, {
        "image": "training/114.png",
        "isSquare": false
    }, {
        "image": "training/115.png",
        "isSquare": true
    }, {
        "image": "training/116.png",
        "isSquare": false
    }, {
        "image": "training/117.png",
        "isSquare": false
    }, {
        "image": "training/118.png",
        "isSquare": false
    }, {
        "image": "training/119.png",
        "isSquare": false
    }, {
        "image": "training/120.png",
        "isSquare": false
    }, {
        "image": "training/121.png",
        "isSquare": true
    }, {
        "image": "training/122.png",
        "isSquare": false
    }, {
        "image": "training/123.png",
        "isSquare": false
    }, {
        "image": "training/124.png",
        "isSquare": false
    }, {
        "image": "training/125.png",
        "isSquare": true
    }, {
        "image": "training/126.png",
        "isSquare": false
    }, {
        "image": "training/127.png",
        "isSquare": false
    }, {
        "image": "training/128.png",
        "isSquare": false
    }, {
        "image": "training/129.png",
        "isSquare": false
    }, {
        "image": "training/130.png",
        "isSquare": false
    }, {
        "image": "training/131.png",
        "isSquare": false
    }, {
        "image": "training/132.png",
        "isSquare": false
    }, {
        "image": "training/133.png",
        "isSquare": false
    }, {
        "image": "training/134.png",
        "isSquare": false
    }, {
        "image": "training/135.png",
        "isSquare": true
    }, {
        "image": "training/136.png",
        "isSquare": false
    }, {
        "image": "training/137.png",
        "isSquare": true
    }, {
        "image": "training/138.png",
        "isSquare": false
    }, {
        "image": "training/139.png",
        "isSquare": false
    }, {
        "image": "training/140.png",
        "isSquare": false
    }, {
        "image": "training/141.png",
        "isSquare": false
    }, {
        "image": "training/142.png",
        "isSquare": false
    }, {
        "image": "training/143.png",
        "isSquare": false
    }, {
        "image": "training/144.png",
        "isSquare": false
    }, {
        "image": "training/145.png",
        "isSquare": false
    }, {
        "image": "training/146.png",
        "isSquare": false
    }, {
        "image": "training/147.png",
        "isSquare": false
    }, {
        "image": "training/148.png",
        "isSquare": false
    }, {
        "image": "training/149.png",
        "isSquare": false
    }, {
        "image": "training/150.png",
        "isSquare": false
    }]
}