import { TrainingExample } from '../interfaces/TrainingExample.interface';

export const TRAINING_DATA: TrainingExample[] = [
    { "image": "training/1.png", "isSquare": true },
    { "image": "training/2.png", "isSquare": true },
    { "image": "training/3.png", "isSquare": true },
    { "image": "training/4.png", "isSquare": true },
    { "image": "training/5.png", "isSquare": true },
    { "image": "training/6.png", "isSquare": true },
    { "image": "training/7.png", "isSquare": true },
    { "image": "training/8.png", "isSquare": true },
    { "image": "training/9.png", "isSquare": true },
    { "image": "training/10.png", "isSquare": true },
    { "image": "training/11.png", "isSquare": false },
    { "image": "training/12.png", "isSquare": false },
    { "image": "training/13.png", "isSquare": false },
    { "image": "training/14.png", "isSquare": false },
    { "image": "training/15.png", "isSquare": false },
    { "image": "training/16.png", "isSquare": false },
    { "image": "training/17.png", "isSquare": false },
    { "image": "training/18.png", "isSquare": false },
    { "image": "training/19.png", "isSquare": false },
    { "image": "training/20.png", "isSquare": false }];